"""
ReportWriter — HackerOne-format bug bounty report generator for HackEmpire X.

Phase 3 feature: Generates professional, ready-to-submit bug bounty reports
in HackerOne format for every verified vulnerability + PoC.

Report format follows HackerOne's recommended structure:
  - Title (clear, specific)
  - Severity (CVSS-aligned)
  - Summary (what the bug is)
  - Steps to Reproduce (numbered, copy-pasteable)
  - Impact (what an attacker can do)
  - Supporting Material (curl commands, screenshots placeholder)
  - Remediation (how to fix)
  - CVSS Score
  - CWE reference
"""
from __future__ import annotations

import json
import logging
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from hackempire.core.models import Vulnerability
from hackempire.ai.poc_generator import ProofOfConcept

logger = logging.getLogger(__name__)

# HackerOne severity mapping
_H1_SEVERITY = {
    "critical": "critical",
    "high":     "high",
    "medium":   "medium",
    "low":      "low",
    "info":     "informational",
}

# CVSS base scores per severity
_CVSS_SCORES = {
    "critical": "9.8",
    "high":     "7.5",
    "medium":   "5.3",
    "low":      "3.1",
    "info":     "0.0",
}


@dataclass
class H1Report:
    title: str
    severity: str
    summary: str
    steps_to_reproduce: list[str]
    impact: str
    supporting_material: str
    remediation: str
    cvss_score: str
    cwe: str
    url: str
    vuln_name: str
    generated_at: str = ""
    ai_generated: bool = False

    def to_markdown(self) -> str:
        """Render as HackerOne-ready Markdown."""
        steps = "\n".join(f"{i+1}. {s}" for i, s in enumerate(self.steps_to_reproduce))
        return f"""## Summary

{self.summary}

## Severity

**{self.severity.upper()}** (CVSS: {self.cvss_score})

## Steps To Reproduce

{steps}

## Impact

{self.impact}

## Supporting Material / References

```
{self.supporting_material}
```

## Remediation

{self.remediation}

---
*CWE: {self.cwe} | URL: {self.url}*
*Generated by HackEmpire X — {self.generated_at}*
"""

    def to_dict(self) -> dict:
        return {
            "title": self.title,
            "severity": self.severity,
            "summary": self.summary,
            "steps_to_reproduce": self.steps_to_reproduce,
            "impact": self.impact,
            "supporting_material": self.supporting_material,
            "remediation": self.remediation,
            "cvss_score": self.cvss_score,
            "cwe": self.cwe,
            "url": self.url,
            "vuln_name": self.vuln_name,
            "generated_at": self.generated_at,
            "ai_generated": self.ai_generated,
        }


class ReportWriter:
    """
    Generates HackerOne-format bug bounty reports.

    Usage:
        writer = ReportWriter(ai_engine=ai_engine)
        reports = writer.generate(vulns, pocs)
        writer.save_all(reports, output_dir="./reports")
    """

    def __init__(self, ai_engine: Any = None) -> None:
        self._ai = ai_engine

    def generate(
        self,
        vulns: list[Vulnerability],
        pocs: list[ProofOfConcept] | None = None,
    ) -> list[H1Report]:
        """Generate H1 report for each vulnerability."""
        poc_map: dict[str, ProofOfConcept] = {}
        if pocs:
            for poc in pocs:
                poc_map[poc.url] = poc

        reports = []
        for vuln in vulns:
            try:
                poc = poc_map.get(vuln.url)
                report = self._generate_one(vuln, poc)
                reports.append(report)
            except Exception as exc:
                logger.warning(f"[report_writer] Failed for {vuln.name}: {exc}")
        return reports

    def save_all(self, reports: list[H1Report], output_dir: str = ".") -> list[str]:
        """Save all reports as Markdown files. Returns list of saved paths."""
        out = Path(output_dir)
        out.mkdir(parents=True, exist_ok=True)
        saved = []
        for i, report in enumerate(reports):
            safe_name = report.vuln_name.lower().replace(" ", "_").replace("/", "_")[:40]
            filename = out / f"h1_report_{i+1:02d}_{safe_name}.md"
            try:
                filename.write_text(report.to_markdown(), encoding="utf-8")
                saved.append(str(filename))
                logger.info(f"[report_writer] Saved: {filename}")
            except Exception as exc:
                logger.warning(f"[report_writer] Save failed: {exc}")
        return saved

    def save_json(self, reports: list[H1Report], output_path: str = "h1_reports.json") -> str:
        """Save all reports as a single JSON file."""
        try:
            data = [r.to_dict() for r in reports]
            Path(output_path).write_text(
                json.dumps(data, indent=2, ensure_ascii=False),
                encoding="utf-8",
            )
            return output_path
        except Exception as exc:
            logger.warning(f"[report_writer] JSON save failed: {exc}")
            return ""

    # ── Internal ─────────────────────────────────────────────────────────

    def _generate_one(self, vuln: Vulnerability, poc: ProofOfConcept | None) -> H1Report:
        # Try AI first
        if self._ai is not None:
            ai_report = self._ai_generate(vuln, poc)
            if ai_report is not None:
                return ai_report
        # Fallback to static template
        return self._static_generate(vuln, poc)

    def _ai_generate(self, vuln: Vulnerability, poc: ProofOfConcept | None) -> H1Report | None:
        try:
            prompt = self._build_report_prompt(vuln, poc)
            response = self._ai._send(prompt)
            if response.get("status_code") != 200 or not response.get("raw_text"):
                return None
            return self._parse_report_response(vuln, response["raw_text"])
        except Exception as exc:
            logger.debug(f"[report_writer] AI report failed: {exc}")
            return None

    def _build_report_prompt(self, vuln: Vulnerability, poc: ProofOfConcept | None) -> str:
        poc_info = ""
        if poc:
            poc_info = (
                f"\nPoC payload: {poc.payload}\n"
                f"Curl command: {poc.curl_command}\n"
                f"Expected response: {poc.expected_response}\n"
            )
        return (
            "You are an expert bug bounty hunter writing a HackerOne report.\n\n"
            f"Vulnerability: {vuln.name}\n"
            f"Severity: {vuln.severity}\n"
            f"URL: {vuln.url}\n"
            f"Evidence: {(vuln.evidence or 'none')[:400]}\n"
            f"CWE: {', '.join(vuln.cwe_ids) if vuln.cwe_ids else 'unknown'}\n"
            f"{poc_info}\n"
            "Write a professional HackerOne bug report.\n\n"
            "OUTPUT FORMAT (strict JSON only):\n"
            "{\n"
            '  "title": "Clear, specific vulnerability title",\n'
            '  "summary": "2-3 sentence description of the vulnerability",\n'
            '  "steps": ["Step 1: ...", "Step 2: ...", "Step 3: ..."],\n'
            '  "impact": "What an attacker can do with this vulnerability",\n'
            '  "remediation": "How to fix this vulnerability"\n'
            "}\n\n"
            "RULES: Output ONLY valid JSON. Be specific and technical. "
            "Steps must be numbered and copy-pasteable."
        )

    def _parse_report_response(self, vuln: Vulnerability, raw_text: str) -> H1Report | None:
        try:
            text = raw_text.strip()
            brace = text.find("{")
            if brace == -1:
                return None
            data = json.loads(text[brace:])
            if not isinstance(data, dict):
                return None
            cwe = ", ".join(vuln.cwe_ids) if vuln.cwe_ids else "CWE-unknown"
            return H1Report(
                title=str(data.get("title", vuln.name)),
                severity=_H1_SEVERITY.get(vuln.severity, "medium"),
                summary=str(data.get("summary", "")),
                steps_to_reproduce=data.get("steps", []),
                impact=str(data.get("impact", "")),
                supporting_material=f"URL: {vuln.url}\nEvidence: {vuln.evidence or 'See steps above'}",
                remediation=str(data.get("remediation", "")),
                cvss_score=_CVSS_SCORES.get(vuln.severity, "5.0"),
                cwe=cwe,
                url=vuln.url,
                vuln_name=vuln.name,
                generated_at=datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC"),
                ai_generated=True,
            )
        except Exception:
            return None

    def _static_generate(self, vuln: Vulnerability, poc: ProofOfConcept | None) -> H1Report:
        """Generate report from static template."""
        cwe = ", ".join(vuln.cwe_ids) if vuln.cwe_ids else "CWE-unknown"
        steps = []
        if poc and poc.steps_to_reproduce:
            steps = poc.steps_to_reproduce
        else:
            steps = [
                f"Navigate to: {vuln.url}",
                f"Identify the vulnerable parameter",
                f"Insert payload and observe the response",
                f"Confirm {vuln.name} vulnerability",
            ]

        supporting = f"URL: {vuln.url}"
        if poc:
            supporting += f"\n\nPoC curl command:\n{poc.curl_command}"
            supporting += f"\n\nPayload used: {poc.payload}"
        if vuln.evidence:
            supporting += f"\n\nEvidence:\n{vuln.evidence[:500]}"

        return H1Report(
            title=f"{vuln.name} in {vuln.url.split('/')[2] if '/' in vuln.url else vuln.url}",
            severity=_H1_SEVERITY.get(vuln.severity, "medium"),
            summary=(
                f"A {vuln.name} vulnerability was discovered at {vuln.url}. "
                f"This vulnerability has {vuln.severity} severity and was detected "
                f"by {', '.join(vuln.tool_sources) if vuln.tool_sources else 'automated scanner'}."
            ),
            steps_to_reproduce=steps,
            impact=poc.impact if poc else f"This {vuln.name} vulnerability could allow an attacker to compromise the application.",
            supporting_material=supporting,
            remediation=poc.remediation if poc else f"Fix the {vuln.name} vulnerability by following OWASP guidelines.",
            cvss_score=_CVSS_SCORES.get(vuln.severity, "5.0"),
            cwe=cwe,
            url=vuln.url,
            vuln_name=vuln.name,
            generated_at=datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC"),
            ai_generated=False,
        )
