"""
ToolKnowledge — AI deep knowledge registry for every integrated tool.

Each entry tells the AI:
  - when_to_use: conditions for selecting this tool
  - what_to_look_for: output patterns indicating a finding
  - success_indicator: machine-checkable success condition
  - failure_action: what to do when tool produces nothing
  - next_tool: recommended follow-up tool on success
  - next_phase_trigger: condition to advance to next phase
"""
from __future__ import annotations

from dataclasses import dataclass
from typing import Literal, Optional


@dataclass(frozen=True)
class ToolKnowledge:
    when_to_use: str
    what_to_look_for: str
    success_indicator: str
    failure_action: Literal["try_next_tool", "skip_phase", "escalate_to_ai"]
    next_tool: Optional[str]
    next_phase_trigger: str


TOOL_KNOWLEDGE: dict[str, ToolKnowledge] = {

    # ── RECON ────────────────────────────────────────────────────────────
    "subfinder": ToolKnowledge(
        when_to_use="Always run first in RECON to enumerate subdomains passively",
        what_to_look_for="Lines containing valid subdomain patterns (e.g. api.target.com)",
        success_indicator="output contains at least one subdomain line",
        failure_action="try_next_tool",
        next_tool="amass",
        next_phase_trigger="5+ subdomains found",
    ),
    "amass": ToolKnowledge(
        when_to_use="Run after subfinder for deeper passive + active subdomain enumeration",
        what_to_look_for="Subdomain lines, ASN info, IP ranges",
        success_indicator="output contains subdomain entries",
        failure_action="try_next_tool",
        next_tool="httpx",
        next_phase_trigger="10+ subdomains found",
    ),
    "httpx": ToolKnowledge(
        when_to_use="Run after subdomain enumeration to probe which hosts are live",
        what_to_look_for="HTTP status codes (200, 301, 302, 403), server headers, titles",
        success_indicator="output contains at least one 200 or 30x response",
        failure_action="try_next_tool",
        next_tool="nmap",
        next_phase_trigger="1+ live hosts found",
    ),
    "dnsx": ToolKnowledge(
        when_to_use="Run to resolve DNS records and validate subdomains",
        what_to_look_for="A records, CNAME records, MX records",
        success_indicator="output contains resolved IP addresses",
        failure_action="try_next_tool",
        next_tool="httpx",
        next_phase_trigger="1+ resolved hosts",
    ),
    "nmap": ToolKnowledge(
        when_to_use="Run for port scanning and service version detection on live hosts",
        what_to_look_for="Open ports, service names, version strings, OS hints",
        success_indicator="output contains 'open' port entries",
        failure_action="try_next_tool",
        next_tool="whatweb",
        next_phase_trigger="web port (80/443/8080/8443) found open",
    ),
    "whatweb": ToolKnowledge(
        when_to_use="Run to fingerprint web technologies (CMS, frameworks, server)",
        what_to_look_for="Technology names: WordPress, Drupal, Apache, Nginx, PHP version",
        success_indicator="output contains technology identifiers",
        failure_action="try_next_tool",
        next_tool="theHarvester",
        next_phase_trigger="CMS or framework identified",
    ),
    "theHarvester": ToolKnowledge(
        when_to_use="Run for OSINT — collect emails, names, IPs from public sources",
        what_to_look_for="Email addresses, employee names, IP ranges, subdomains",
        success_indicator="output contains email or subdomain entries",
        failure_action="try_next_tool",
        next_tool="recon-ng",
        next_phase_trigger="email addresses or additional subdomains found",
    ),
    "recon-ng": ToolKnowledge(
        when_to_use="Run for deep OSINT using modular framework",
        what_to_look_for="Contacts, credentials, hosts, vulnerabilities from public sources",
        success_indicator="output contains host or contact records",
        failure_action="try_next_tool",
        next_tool="dnsenum",
        next_phase_trigger="new hosts or contacts discovered",
    ),
    "dnsenum": ToolKnowledge(
        when_to_use="Run for DNS zone transfer attempts and brute force",
        what_to_look_for="Zone transfer success, additional subdomains, MX/NS records",
        success_indicator="output contains DNS records or zone transfer data",
        failure_action="try_next_tool",
        next_tool="fierce",
        next_phase_trigger="zone transfer successful or 5+ new subdomains",
    ),
    "fierce": ToolKnowledge(
        when_to_use="Run for DNS brute force subdomain discovery",
        what_to_look_for="Subdomain lines with IP addresses",
        success_indicator="output contains resolved subdomain entries",
        failure_action="skip_phase",
        next_tool=None,
        next_phase_trigger="new subdomains discovered",
    ),
    "shuffledns": ToolKnowledge(
        when_to_use="Run for fast DNS brute force with wordlist",
        what_to_look_for="Valid subdomain resolutions",
        success_indicator="output contains resolved subdomains",
        failure_action="try_next_tool",
        next_tool="httpx",
        next_phase_trigger="5+ new subdomains resolved",
    ),
    "assetfinder": ToolKnowledge(
        when_to_use="Run for quick passive subdomain discovery",
        what_to_look_for="Subdomain lines",
        success_indicator="output contains subdomain entries",
        failure_action="try_next_tool",
        next_tool="httpx",
        next_phase_trigger="subdomains found",
    ),
    "github-subdomains": ToolKnowledge(
        when_to_use="Run to find subdomains leaked in GitHub repositories",
        what_to_look_for="Subdomain patterns in code/config files",
        success_indicator="output contains subdomain entries",
        failure_action="try_next_tool",
        next_tool="httpx",
        next_phase_trigger="new subdomains found",
    ),
}

# ── URL DISCOVERY ─────────────────────────────────────────────────────
TOOL_KNOWLEDGE.update({
    "katana": ToolKnowledge(
        when_to_use="Run to crawl target for URLs and endpoints",
        what_to_look_for="URLs with parameters, API endpoints, JS files",
        success_indicator="output contains URL entries",
        failure_action="try_next_tool",
        next_tool="gau",
        next_phase_trigger="50+ URLs discovered",
    ),
    "gau": ToolKnowledge(
        when_to_use="Run to fetch known URLs from Wayback Machine and other archives",
        what_to_look_for="Historical URLs with parameters",
        success_indicator="output contains URL entries",
        failure_action="try_next_tool",
        next_tool="waybackurls",
        next_phase_trigger="URLs with parameters found",
    ),
    "waybackurls": ToolKnowledge(
        when_to_use="Run to pull historical URLs from Wayback Machine",
        what_to_look_for="URLs with query parameters",
        success_indicator="output contains URL entries",
        failure_action="try_next_tool",
        next_tool="hakrawler",
        next_phase_trigger="URLs with parameters found",
    ),
    "hakrawler": ToolKnowledge(
        when_to_use="Run for deep link discovery via crawling",
        what_to_look_for="Internal links, forms, API endpoints",
        success_indicator="output contains URL entries",
        failure_action="try_next_tool",
        next_tool="gospider",
        next_phase_trigger="new endpoints discovered",
    ),
    "gospider": ToolKnowledge(
        when_to_use="Run for spider-based URL collection",
        what_to_look_for="URLs, forms, JS files",
        success_indicator="output contains URL entries",
        failure_action="try_next_tool",
        next_tool="cariddi",
        next_phase_trigger="new endpoints discovered",
    ),
    "cariddi": ToolKnowledge(
        when_to_use="Run for endpoint and secret discovery in crawled content",
        what_to_look_for="API keys, secrets, endpoints in JS/HTML",
        success_indicator="output contains endpoint or secret entries",
        failure_action="try_next_tool",
        next_tool="waymore",
        next_phase_trigger="secrets or new endpoints found",
    ),
    "waymore": ToolKnowledge(
        when_to_use="Run for comprehensive URL harvesting from multiple sources",
        what_to_look_for="URLs with parameters from Wayback, CommonCrawl, OTX",
        success_indicator="output contains URL entries",
        failure_action="try_next_tool",
        next_tool=None,
        next_phase_trigger="100+ URLs collected",
    ),
    "anew": ToolKnowledge(
        when_to_use="Run to deduplicate URL lists from multiple tools",
        what_to_look_for="Unique URL entries",
        success_indicator="output contains deduplicated URLs",
        failure_action="try_next_tool",
        next_tool=None,
        next_phase_trigger="unique URLs ready for enumeration",
    ),
    "qsreplace": ToolKnowledge(
        when_to_use="Run to replace query string values for fuzzing preparation",
        what_to_look_for="Modified URLs ready for injection testing",
        success_indicator="output contains modified URL entries",
        failure_action="try_next_tool",
        next_tool=None,
        next_phase_trigger="URLs prepared for fuzzing",
    ),
})

# ── ENUMERATION ───────────────────────────────────────────────────────
TOOL_KNOWLEDGE.update({
    "feroxbuster": ToolKnowledge(
        when_to_use="Run for recursive directory and file brute-forcing",
        what_to_look_for="200/301/302 responses, admin panels, backup files, config files",
        success_indicator="output contains 200 or 30x status responses",
        failure_action="try_next_tool",
        next_tool="ffuf",
        next_phase_trigger="admin panel or sensitive file found",
    ),
    "ffuf": ToolKnowledge(
        when_to_use="Run for fast parameter and path fuzzing",
        what_to_look_for="Different response sizes/codes indicating valid paths or params",
        success_indicator="output contains non-404 responses",
        failure_action="try_next_tool",
        next_tool="dirsearch",
        next_phase_trigger="hidden parameters or paths discovered",
    ),
    "dirsearch": ToolKnowledge(
        when_to_use="Run for directory enumeration with comprehensive wordlist",
        what_to_look_for="200/301/403 responses, backup files (.bak, .old), config files",
        success_indicator="output contains non-404 status codes",
        failure_action="try_next_tool",
        next_tool="arjun",
        next_phase_trigger="sensitive files or directories found",
    ),
    "arjun": ToolKnowledge(
        when_to_use="Run to discover hidden HTTP parameters in endpoints",
        what_to_look_for="Parameter names that change response behavior",
        success_indicator="output contains discovered parameter names",
        failure_action="try_next_tool",
        next_tool="kiterunner",
        next_phase_trigger="hidden parameters found",
    ),
    "kiterunner": ToolKnowledge(
        when_to_use="Run for API route discovery using real-world wordlists",
        what_to_look_for="API endpoints returning 200/201/204",
        success_indicator="output contains valid API routes",
        failure_action="try_next_tool",
        next_tool="paramspider",
        next_phase_trigger="API endpoints discovered",
    ),
    "paramspider": ToolKnowledge(
        when_to_use="Run to mine parameters from URLs in web archives",
        what_to_look_for="Parameter names from historical URLs",
        success_indicator="output contains parameter entries",
        failure_action="try_next_tool",
        next_tool="gobuster",
        next_phase_trigger="parameters found for injection testing",
    ),
    "gobuster": ToolKnowledge(
        when_to_use="Run for directory/DNS/vhost brute force",
        what_to_look_for="Valid directories, subdomains, virtual hosts",
        success_indicator="output contains found entries",
        failure_action="try_next_tool",
        next_tool="wfuzz",
        next_phase_trigger="new attack surface discovered",
    ),
    "wfuzz": ToolKnowledge(
        when_to_use="Run for web fuzzing with filter engine",
        what_to_look_for="Responses with different sizes/codes from baseline",
        success_indicator="output contains non-baseline responses",
        failure_action="try_next_tool",
        next_tool="WPProbe",
        next_phase_trigger="interesting responses found",
    ),
    "WPProbe": ToolKnowledge(
        when_to_use="Run when WordPress is detected to enumerate plugins",
        what_to_look_for="Plugin names and versions, vulnerable plugin indicators",
        success_indicator="output contains plugin entries",
        failure_action="try_next_tool",
        next_tool="wpscan",
        next_phase_trigger="vulnerable plugins found",
    ),
    "wpscan": ToolKnowledge(
        when_to_use="Run when WordPress is detected for full vulnerability scan",
        what_to_look_for="CVEs, vulnerable plugins/themes, user enumeration",
        success_indicator="output contains vulnerability entries",
        failure_action="try_next_tool",
        next_tool="joomscan",
        next_phase_trigger="WordPress vulnerabilities found",
    ),
    "joomscan": ToolKnowledge(
        when_to_use="Run when Joomla is detected",
        what_to_look_for="Joomla version, vulnerable extensions, misconfigurations",
        success_indicator="output contains vulnerability entries",
        failure_action="try_next_tool",
        next_tool=None,
        next_phase_trigger="Joomla vulnerabilities found",
    ),
    "smbmap": ToolKnowledge(
        when_to_use="Run when SMB port (445) is open to enumerate shares",
        what_to_look_for="Readable/writable shares, sensitive files",
        success_indicator="output contains share entries",
        failure_action="try_next_tool",
        next_tool="enum4linux-ng",
        next_phase_trigger="accessible shares found",
    ),
    "enum4linux-ng": ToolKnowledge(
        when_to_use="Run when SMB/NetBIOS is available for AD enumeration",
        what_to_look_for="Users, groups, shares, password policies",
        success_indicator="output contains user or share entries",
        failure_action="try_next_tool",
        next_tool=None,
        next_phase_trigger="AD users or shares enumerated",
    ),
    "ldapdomaindump": ToolKnowledge(
        when_to_use="Run when LDAP is accessible to dump AD structure",
        what_to_look_for="Users, groups, computers, GPOs",
        success_indicator="output contains LDAP entries",
        failure_action="try_next_tool",
        next_tool=None,
        next_phase_trigger="AD structure dumped",
    ),
})

# ── VULN SCAN ─────────────────────────────────────────────────────────
TOOL_KNOWLEDGE.update({
    "nuclei": ToolKnowledge(
        when_to_use="Run with full template set for CVE and misconfiguration detection",
        what_to_look_for="Template matches: critical/high/medium severity findings",
        success_indicator="output contains [critical] or [high] or [medium] findings",
        failure_action="try_next_tool",
        next_tool="afrog",
        next_phase_trigger="any severity >= medium finding confirmed",
    ),
    "afrog": ToolKnowledge(
        when_to_use="Run for fast vulnerability scanning with 300+ PoC checks",
        what_to_look_for="Vulnerability confirmations with severity levels",
        success_indicator="output contains vulnerability entries",
        failure_action="try_next_tool",
        next_tool="nikto",
        next_phase_trigger="exploitable vulnerability found",
    ),
    "nikto": ToolKnowledge(
        when_to_use="Run for web server misconfiguration and known vulnerability scanning",
        what_to_look_for="OSVDB entries, dangerous files, server misconfigurations",
        success_indicator="output contains OSVDB or vulnerability entries",
        failure_action="try_next_tool",
        next_tool="naabu",
        next_phase_trigger="server misconfiguration found",
    ),
    "naabu": ToolKnowledge(
        when_to_use="Run for fast port scanning when nmap is too slow",
        what_to_look_for="Open ports, especially non-standard web ports",
        success_indicator="output contains open port entries",
        failure_action="try_next_tool",
        next_tool="interactsh-client",
        next_phase_trigger="new open ports discovered",
    ),
    "interactsh-client": ToolKnowledge(
        when_to_use="Run to detect blind SSRF, XXE, RCE via OOB interactions",
        what_to_look_for="DNS/HTTP callbacks from target to interactsh server",
        success_indicator="output contains interaction callbacks",
        failure_action="try_next_tool",
        next_tool="sslyze",
        next_phase_trigger="OOB interaction confirmed",
    ),
    "sslyze": ToolKnowledge(
        when_to_use="Run when HTTPS is present to analyze TLS configuration",
        what_to_look_for="Weak ciphers, expired certs, BEAST/POODLE/Heartbleed",
        success_indicator="output contains vulnerability or misconfiguration entries",
        failure_action="try_next_tool",
        next_tool="SSTImap",
        next_phase_trigger="TLS vulnerability found",
    ),
    "SSTImap": ToolKnowledge(
        when_to_use="Run when template rendering is suspected (Jinja2, Twig, Freemarker)",
        what_to_look_for="Template injection confirmation ({{7*7}} = 49)",
        success_indicator="output contains SSTI confirmation",
        failure_action="try_next_tool",
        next_tool="zaproxy",
        next_phase_trigger="SSTI confirmed",
    ),
    "zaproxy": ToolKnowledge(
        when_to_use="Run for comprehensive OWASP ZAP web application scanning",
        what_to_look_for="XSS, SQLi, CSRF, security headers, injection points",
        success_indicator="output contains alert entries",
        failure_action="try_next_tool",
        next_tool="semgrep",
        next_phase_trigger="high/medium severity alerts found",
    ),
    "semgrep": ToolKnowledge(
        when_to_use="Run when source code is accessible for static analysis",
        what_to_look_for="Hardcoded secrets, SQL injection patterns, insecure functions",
        success_indicator="output contains finding entries",
        failure_action="try_next_tool",
        next_tool=None,
        next_phase_trigger="code vulnerabilities found",
    ),
    "dalfox": ToolKnowledge(
        when_to_use="Run for XSS detection and exploitation on discovered URLs",
        what_to_look_for="XSS confirmation with payload and affected parameter",
        success_indicator="output contains XSS confirmation",
        failure_action="try_next_tool",
        next_tool="ghauri",
        next_phase_trigger="XSS confirmed",
    ),
    "ghauri": ToolKnowledge(
        when_to_use="Run for SQL injection detection on parameterized URLs",
        what_to_look_for="Injectable parameter confirmation, DBMS identification",
        success_indicator="output contains injection confirmation",
        failure_action="try_next_tool",
        next_tool="testssl",
        next_phase_trigger="SQLi confirmed",
    ),
    "testssl": ToolKnowledge(
        when_to_use="Run for deep TLS/SSL analysis on HTTPS endpoints",
        what_to_look_for="Protocol weaknesses, cipher issues, certificate problems",
        success_indicator="output contains WARN or VULNERABLE entries",
        failure_action="skip_phase",
        next_tool=None,
        next_phase_trigger="TLS vulnerability found",
    ),
    "wafw00f": ToolKnowledge(
        when_to_use="Run at start of VULN_SCAN to detect WAF before other tools",
        what_to_look_for="WAF vendor name and confidence",
        success_indicator="output contains WAF detection result",
        failure_action="try_next_tool",
        next_tool="nuclei",
        next_phase_trigger="WAF vendor identified for bypass",
    ),
    "jsluice": ToolKnowledge(
        when_to_use="Run on JS files to extract secrets and endpoints",
        what_to_look_for="API keys, tokens, internal URLs, hardcoded credentials",
        success_indicator="output contains secret or endpoint entries",
        failure_action="try_next_tool",
        next_tool=None,
        next_phase_trigger="secrets or internal endpoints found",
    ),
})

# ── EXPLOITATION ──────────────────────────────────────────────────────
TOOL_KNOWLEDGE.update({
    "sqlmap": ToolKnowledge(
        when_to_use="Run when SQLi is suspected or confirmed to exploit and extract data",
        what_to_look_for="Database names, tables, data dump, OS shell access",
        success_indicator="output contains 'is vulnerable' or database entries",
        failure_action="try_next_tool",
        next_tool="xsstrike",
        next_phase_trigger="database dumped or OS shell obtained",
    ),
    "xsstrike": ToolKnowledge(
        when_to_use="Run for advanced XSS exploitation with WAF bypass",
        what_to_look_for="XSS payload confirmation, DOM sinks",
        success_indicator="output contains XSS confirmation",
        failure_action="try_next_tool",
        next_tool="commix",
        next_phase_trigger="XSS exploited",
    ),
    "commix": ToolKnowledge(
        when_to_use="Run when command injection is suspected",
        what_to_look_for="Command execution confirmation, shell access",
        success_indicator="output contains command output or shell prompt",
        failure_action="try_next_tool",
        next_tool="tplmap",
        next_phase_trigger="command injection confirmed",
    ),
    "tplmap": ToolKnowledge(
        when_to_use="Run when SSTI is suspected for exploitation",
        what_to_look_for="Template engine identification, RCE via template",
        success_indicator="output contains engine identification or RCE confirmation",
        failure_action="try_next_tool",
        next_tool="MetasploitMCP",
        next_phase_trigger="SSTI exploited to RCE",
    ),
    "MetasploitMCP": ToolKnowledge(
        when_to_use="Run for exploit framework when CVE or service vulnerability is confirmed",
        what_to_look_for="Meterpreter session, shell access, exploit success",
        success_indicator="output contains session opened or shell prompt",
        failure_action="try_next_tool",
        next_tool="ysoserial",
        next_phase_trigger="Meterpreter session obtained",
    ),
    "ysoserial": ToolKnowledge(
        when_to_use="Run when Java deserialization vulnerability is suspected",
        what_to_look_for="RCE via deserialization payload",
        success_indicator="output contains command execution confirmation",
        failure_action="try_next_tool",
        next_tool="certipy",
        next_phase_trigger="deserialization RCE confirmed",
    ),
    "certipy": ToolKnowledge(
        when_to_use="Run when Active Directory Certificate Services is present",
        what_to_look_for="Vulnerable certificate templates, ESC1-ESC8 attacks",
        success_indicator="output contains vulnerable template or certificate",
        failure_action="skip_phase",
        next_tool=None,
        next_phase_trigger="AD CS vulnerability confirmed",
    ),
    "metasploit": ToolKnowledge(
        when_to_use="Run for exploit framework (msfconsole) when specific CVE is confirmed",
        what_to_look_for="Session opened, shell access, privilege escalation",
        success_indicator="output contains 'session' or 'shell'",
        failure_action="try_next_tool",
        next_tool=None,
        next_phase_trigger="shell or session obtained",
    ),
})

# ── POST_EXPLOIT ──────────────────────────────────────────────────────
TOOL_KNOWLEDGE.update({
    "linpeas": ToolKnowledge(
        when_to_use="Run after gaining shell access for Linux privilege escalation enumeration",
        what_to_look_for="SUID binaries, writable paths, cron jobs, sudo misconfigs",
        success_indicator="output contains privilege escalation vectors",
        failure_action="try_next_tool",
        next_tool="netexec",
        next_phase_trigger="privilege escalation path found",
    ),
    "netexec": ToolKnowledge(
        when_to_use="Run for SMB/WinRM/LDAP lateral movement with credentials",
        what_to_look_for="Successful authentication, accessible shares, command execution",
        success_indicator="output contains successful auth or command output",
        failure_action="try_next_tool",
        next_tool="chisel",
        next_phase_trigger="lateral movement successful",
    ),
    "chisel": ToolKnowledge(
        when_to_use="Run to create TCP tunnel for pivoting to internal network",
        what_to_look_for="Tunnel established, internal hosts accessible",
        success_indicator="output contains tunnel connection confirmation",
        failure_action="try_next_tool",
        next_tool="ligolo-ng",
        next_phase_trigger="internal network accessible",
    ),
    "ligolo-ng": ToolKnowledge(
        when_to_use="Run for reverse tunnel and network pivoting",
        what_to_look_for="Tunnel established, routing to internal subnet",
        success_indicator="output contains tunnel or routing confirmation",
        failure_action="try_next_tool",
        next_tool="impacket",
        next_phase_trigger="internal network pivoting established",
    ),
    "impacket": ToolKnowledge(
        when_to_use="Run for Windows exploitation: secretsdump, psexec, wmiexec",
        what_to_look_for="NTLM hashes, Kerberos tickets, command execution",
        success_indicator="output contains hash entries or command output",
        failure_action="try_next_tool",
        next_tool="bloodhound",
        next_phase_trigger="credentials or hashes obtained",
    ),
    "bloodhound": ToolKnowledge(
        when_to_use="Run to map Active Directory attack paths",
        what_to_look_for="Shortest path to Domain Admin, ACL abuses, Kerberoastable accounts",
        success_indicator="output contains attack path data",
        failure_action="try_next_tool",
        next_tool="AdaptixC2",
        next_phase_trigger="path to Domain Admin found",
    ),
    "AdaptixC2": ToolKnowledge(
        when_to_use="Run for C2 framework post-exploitation and adversary emulation",
        what_to_look_for="Agent check-in, command execution, persistence",
        success_indicator="output contains agent connection",
        failure_action="try_next_tool",
        next_tool="Atomic-Operator",
        next_phase_trigger="C2 agent established",
    ),
    "Atomic-Operator": ToolKnowledge(
        when_to_use="Run to execute MITRE ATT&CK atomic tests for detection validation",
        what_to_look_for="Test execution results, detection gaps",
        success_indicator="output contains test execution results",
        failure_action="try_next_tool",
        next_tool="pypykatz",
        next_phase_trigger="ATT&CK techniques tested",
    ),
    "pypykatz": ToolKnowledge(
        when_to_use="Run for credential dumping from LSASS memory (Python mimikatz)",
        what_to_look_for="NTLM hashes, plaintext passwords, Kerberos tickets",
        success_indicator="output contains credential entries",
        failure_action="try_next_tool",
        next_tool="pspy",
        next_phase_trigger="credentials dumped",
    ),
    "pspy": ToolKnowledge(
        when_to_use="Run to monitor processes without root for privilege escalation clues",
        what_to_look_for="Cron jobs running as root, scripts with weak permissions",
        success_indicator="output contains privileged process entries",
        failure_action="try_next_tool",
        next_tool="evil-winrm",
        next_phase_trigger="privilege escalation opportunity found",
    ),
    "evil-winrm": ToolKnowledge(
        when_to_use="Run when WinRM (5985/5986) is open and credentials are available",
        what_to_look_for="Interactive shell, file upload/download, command execution",
        success_indicator="output contains shell prompt or command output",
        failure_action="skip_phase",
        next_tool=None,
        next_phase_trigger="WinRM shell obtained",
    ),
    "crackmapexec": ToolKnowledge(
        when_to_use="Run for SMB/WinRM/LDAP lateral movement and credential spraying",
        what_to_look_for="Successful authentication markers, accessible shares, command execution output",
        success_indicator="output contains [+] or successful auth or command output",
        failure_action="try_next_tool",
        next_tool="impacket",
        next_phase_trigger="lateral movement successful or credentials confirmed",
    ),
    "trufflehog": ToolKnowledge(
        when_to_use="Run to scan for secrets in git repos, files, and environment",
        what_to_look_for="API keys, tokens, passwords, private keys",
        success_indicator="output contains secret entries",
        failure_action="try_next_tool",
        next_tool=None,
        next_phase_trigger="secrets found",
    ),
    "ldapdomaindump": ToolKnowledge(
        when_to_use="Run when LDAP credentials are available to dump AD structure",
        what_to_look_for="Users, groups, computers, GPOs, password policies",
        success_indicator="output contains LDAP dump files",
        failure_action="try_next_tool",
        next_tool=None,
        next_phase_trigger="AD structure dumped",
    ),
})
